# -*- coding: utf-8 -*-
"""
esg.recommendation — Data-grounded action items for employees/departments.

This is what the Employee dashboard calls "My ESG Action Items" — NOT a generic
to-do list. Every record has provenance: a `metric_id` pointing to the specific
ESG gap it addresses, and a `score_id` pointing to the score that triggered it.

Records are generated by either:
  - Phase 2 rule-based engine (is_ai_generated=False)
  - Phase 3 Grok AI layer (is_ai_generated=True)

Both paths write to this same model; the UI renders them identically. This
satisfies the "core works offline" constraint: rule-based recommendations always
exist even when Grok is unavailable.
"""
from odoo import fields, models


class EsgRecommendation(models.Model):
    _name = 'esg.recommendation'
    _description = 'ESG Recommendation / Action Item'
    _order = 'priority, create_date desc'
    _inherit = ['mail.thread']

    title = fields.Char(string='Action Title', required=True)
    description = fields.Text(string='Description')

    # ------------------------------------------------------------------ #
    # Scope                                                               #
    # ------------------------------------------------------------------ #
    scope = fields.Selection(
        selection=[
            ('employee', 'Employee'),
            ('department', 'Department'),
            ('org', 'Organisation'),
        ],
        string='Scope',
        required=True,
        default='employee',
        index=True,
    )
    employee_id = fields.Many2one(
        comodel_name='hr.employee',
        string='Employee',
        ondelete='cascade',
        index=True,
    )
    department_id = fields.Many2one(
        comodel_name='hr.department',
        string='Department',
        ondelete='cascade',
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Provenance — what gap this addresses                                #
    # ------------------------------------------------------------------ #
    metric_id = fields.Many2one(
        comodel_name='esg.metric',
        string='Related Metric',
        ondelete='set null',
        help='The specific ESG metric gap this recommendation addresses.',
    )
    score_id = fields.Many2one(
        comodel_name='esg.score',
        string='Source Score',
        ondelete='set null',
        help='The esg.score record that generated this recommendation.',
    )

    # ------------------------------------------------------------------ #
    # Priority & state                                                    #
    # ------------------------------------------------------------------ #
    priority = fields.Selection(
        selection=[
            ('high', 'High'),
            ('medium', 'Medium'),
            ('low', 'Low'),
        ],
        string='Priority',
        default='medium',
        index=True,
    )
    state = fields.Selection(
        selection=[
            ('open', 'Open'),
            ('in_progress', 'In Progress'),
            ('done', 'Done'),
            ('dismissed', 'Dismissed'),
        ],
        string='Status',
        default='open',
        index=True,
        tracking=True,
    )
    due_date = fields.Date(string='Due Date')
    is_ai_generated = fields.Boolean(
        string='AI Generated',
        default=False,
        help='True = authored by Grok (Phase 3); False = rule-based engine.',
    )

    # ------------------------------------------------------------------ #
    # Gamification link                                                   #
    # ------------------------------------------------------------------ #
    xp_reward = fields.Integer(
        string='XP Reward',
        default=0,
        help='XP written to esg.xp.ledger when this action item is marked Done.',
    )
