# -*- coding: utf-8 -*-
"""
esg.goal — Personalised sustainability goal per employee or department.

Handles live current value computation via EsgDataAggregator and triggers
ledger XP writes on goal achievement.
"""
from odoo import api, fields, models
from odoo.exceptions import ValidationError
from datetime import date, timedelta


class EsgGoal(models.Model):
    _name = 'esg.goal'
    _description = 'ESG Personalised Goal'
    _order = 'period_end, scope, state'

    name = fields.Char(string='Goal Name', required=True)

    # ------------------------------------------------------------------ #
    # Scope                                                               #
    # ------------------------------------------------------------------ #
    scope = fields.Selection(
        selection=[
            ('employee', 'Employee'),
            ('department', 'Department'),
        ],
        string='Scope',
        required=True,
        default='employee',
        index=True,
    )
    employee_id = fields.Many2one(
        comodel_name='hr.employee',
        string='Employee',
        ondelete='cascade',
        index=True,
    )
    department_id = fields.Many2one(
        comodel_name='hr.department',
        string='Department',
        ondelete='cascade',
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Target                                                              #
    # ------------------------------------------------------------------ #
    metric_id = fields.Many2one(
        comodel_name='esg.metric',
        string='Target Metric',
        required=True,
        ondelete='restrict',
    )
    target_value = fields.Float(string='Target Value', required=True)
    baseline_value = fields.Float(
        string='Baseline Value',
        help='Metric value when this goal was created (snapshotted).',
    )
    current_value = fields.Float(
        string='Current Value',
        compute='_compute_current_value',
        store=False,
        help='Live metric value; computed from EsgDataAggregator.',
    )
    progress_pct = fields.Float(
        string='Progress (%)',
        compute='_compute_progress_pct',
        store=False,
        digits=(5, 1),
    )

    period_start = fields.Date(string='Start Date', required=True)
    period_end = fields.Date(string='Due Date', required=True)

    state = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('achieved', 'Achieved'),
            ('missed', 'Missed'),
            ('cancelled', 'Cancelled'),
        ],
        string='Status',
        default='active',
        index=True,
    )
    is_ai_suggested = fields.Boolean(
        string='AI Suggested',
        default=False,
        help='True = generated by Grok coaching engine.',
    )
    coaching_notes = fields.Text(
        string='Coaching Notes',
        help='Grok-generated coaching advice. Empty = graceful fallback in UI.',
    )

    # ------------------------------------------------------------------ #
    # Computations                                                         #
    # ------------------------------------------------------------------ #
    def _compute_current_value(self):
        """Query live metric value from native Odoo model."""
        aggregator = self.env['esg.data.aggregator']
        for rec in self:
            target_id = rec.employee_id.id if rec.scope == 'employee' else rec.department_id.id
            rec.current_value = aggregator.get_raw_value(
                rec.metric_id, rec.scope, target_id, rec.period_start, rec.period_end
            )

    @api.depends('current_value', 'baseline_value', 'target_value')
    def _compute_progress_pct(self):
        for rec in self:
            span = rec.target_value - rec.baseline_value
            if span == 0:
                rec.progress_pct = 100.0 if rec.current_value >= rec.target_value else 0.0
            else:
                rec.progress_pct = min(
                    100.0,
                    max(
                        0.0,
                        abs(rec.current_value - rec.baseline_value) / abs(span) * 100,
                    ),
                )

    @api.constrains('period_start', 'period_end')
    def _check_period(self):
        for rec in self:
            if rec.period_start and rec.period_end:
                if rec.period_start > rec.period_end:
                    raise ValidationError('Start Date must be before Due Date.')

    # ------------------------------------------------------------------ #
    # Onboarding flow onboarding wizard triggers                          #
    # ------------------------------------------------------------------ #
    @api.model
    def check_or_create_onboarding_goal(self, employee):
        """Creates a default goal if the employee has none active."""
        active_goals = self.search_count([
            ('scope', '=', 'employee'),
            ('employee_id', '=', employee.id),
            ('state', '=', 'active')
        ])
        if active_goals == 0:
            # Seed default metric
            metric = self.env['esg.metric'].search([], limit=1)
            if metric:
                self.create({
                    'name': 'First Step: Initial ESG Action Plan',
                    'scope': 'employee',
                    'employee_id': employee.id,
                    'metric_id': metric.id,
                    'baseline_value': metric.min_value,
                    'target_value': (metric.min_value + metric.max_value) / 2.0,
                    'period_start': date.today(),
                    'period_end': date.today() + timedelta(days=14),
                    'state': 'active',
                    'coaching_notes': 'Welcome to EcoSphere! Try planting a tree or checking in on time to complete your first goal.',
                })

    # ------------------------------------------------------------------ #
    # Phase 5: Gamification triggers & anti-double-award checks          #
    # ------------------------------------------------------------------ #
    def write(self, vals):
        """Trigger XP ledger write when state changes to achieved."""
        if 'state' in vals and vals['state'] == 'achieved':
            for rec in self:
                if rec.state != 'achieved' and rec.scope == 'employee' and rec.employee_id:
                    self.env['esg.xp.ledger'].create({
                        'employee_id': rec.employee_id.id,
                        'delta_xp': 200,  # 200 XP for achieving a personalized goal
                        'reason': 'challenge_complete',
                        'reference_model': 'esg.goal',
                        'reference_id': rec.id,
                        'verified_by_data': True,
                        'notes': f"Personalized goal achieved: {rec.name}",
                    })
        return super(EsgGoal, self).write(vals)
