# -*- coding: utf-8 -*-
"""
esg.goal — Personalised sustainability goal per employee or department.

Goals are generated by:
  - Phase 5 onboarding flow (first goal, always created on first login)
  - Phase 3/5 Grok coaching engine (is_ai_suggested=True)
  - Manually by employees or managers

`baseline_value` is snapshotted when the goal is created.
`current_value` is a live-computed field (Phase 2 implements the computation).
Progress % = abs(current_value - baseline_value) / abs(target_value - baseline_value) * 100
"""
from odoo import api, fields, models
from odoo.exceptions import ValidationError


class EsgGoal(models.Model):
    _name = 'esg.goal'
    _description = 'ESG Personalised Goal'
    _order = 'period_end, scope, state'

    name = fields.Char(string='Goal Name', required=True)

    # ------------------------------------------------------------------ #
    # Scope                                                               #
    # ------------------------------------------------------------------ #
    scope = fields.Selection(
        selection=[
            ('employee', 'Employee'),
            ('department', 'Department'),
        ],
        string='Scope',
        required=True,
        default='employee',
        index=True,
    )
    employee_id = fields.Many2one(
        comodel_name='hr.employee',
        string='Employee',
        ondelete='cascade',
        index=True,
    )
    department_id = fields.Many2one(
        comodel_name='hr.department',
        string='Department',
        ondelete='cascade',
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Target                                                              #
    # ------------------------------------------------------------------ #
    metric_id = fields.Many2one(
        comodel_name='esg.metric',
        string='Target Metric',
        required=True,
        ondelete='restrict',
    )
    target_value = fields.Float(string='Target Value', required=True)
    baseline_value = fields.Float(
        string='Baseline Value',
        help='Metric value when this goal was created (snapshotted).',
    )
    current_value = fields.Float(
        string='Current Value',
        compute='_compute_current_value',
        store=False,
        help='Live metric value; Phase 2 implements the computation.',
    )
    progress_pct = fields.Float(
        string='Progress (%)',
        compute='_compute_progress_pct',
        store=False,
        digits=(5, 1),
    )

    period_start = fields.Date(string='Start Date', required=True)
    period_end = fields.Date(string='Due Date', required=True)

    state = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('achieved', 'Achieved'),
            ('missed', 'Missed'),
            ('cancelled', 'Cancelled'),
        ],
        string='Status',
        default='active',
        index=True,
    )
    is_ai_suggested = fields.Boolean(
        string='AI Suggested',
        default=False,
        help='True = generated by Grok coaching engine.',
    )
    coaching_notes = fields.Text(
        string='Coaching Notes',
        help='Grok-generated coaching advice. Empty = graceful fallback in UI.',
    )

    # ------------------------------------------------------------------ #
    # Phase 1 stubs — Phase 2 will implement these                       #
    # ------------------------------------------------------------------ #
    def _compute_current_value(self):
        """Phase 2: query live metric value from native Odoo model."""
        for rec in self:
            rec.current_value = 0.0  # stub

    @api.depends('current_value', 'baseline_value', 'target_value')
    def _compute_progress_pct(self):
        for rec in self:
            span = rec.target_value - rec.baseline_value
            if span == 0:
                rec.progress_pct = 100.0 if rec.current_value >= rec.target_value else 0.0
            else:
                rec.progress_pct = min(
                    100.0,
                    max(
                        0.0,
                        abs(rec.current_value - rec.baseline_value) / abs(span) * 100,
                    ),
                )

    @api.constrains('period_start', 'period_end')
    def _check_period(self):
        for rec in self:
            if rec.period_start and rec.period_end:
                if rec.period_start > rec.period_end:
                    raise ValidationError('Start Date must be before Due Date.')
